name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        shell: bash
        run: |
          pip install --no-deps -r ./lock/requirements-dev.txt
          pip install --no-deps .

      - id: pytest
        run: |
          pytest \
            --cov=src \
            --cov-report=xml \
            tests

      - id: coveralls
        name: Upload coverage to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
